# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AuthResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token_type: str=None, expires_in: int=None, access_token: str=None):  # noqa: E501
        """AuthResponse - a model defined in Swagger

        :param token_type: The token_type of this AuthResponse.  # noqa: E501
        :type token_type: str
        :param expires_in: The expires_in of this AuthResponse.  # noqa: E501
        :type expires_in: int
        :param access_token: The access_token of this AuthResponse.  # noqa: E501
        :type access_token: str
        """
        self.swagger_types = {
            'token_type': str,
            'expires_in': int,
            'access_token': str
        }

        self.attribute_map = {
            'token_type': 'tokenType',
            'expires_in': 'expiresIn',
            'access_token': 'accessToken'
        }
        self._token_type = token_type
        self._expires_in = expires_in
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'AuthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthResponse of this AuthResponse.  # noqa: E501
        :rtype: AuthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token_type(self) -> str:
        """Gets the token_type of this AuthResponse.

        Tipo de token (siempre 'Bearer')  # noqa: E501

        :return: The token_type of this AuthResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this AuthResponse.

        Tipo de token (siempre 'Bearer')  # noqa: E501

        :param token_type: The token_type of this AuthResponse.
        :type token_type: str
        """

        self._token_type = token_type

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this AuthResponse.

        Tiempo de expiración del token en segundos  # noqa: E501

        :return: The expires_in of this AuthResponse.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this AuthResponse.

        Tiempo de expiración del token en segundos  # noqa: E501

        :param expires_in: The expires_in of this AuthResponse.
        :type expires_in: int
        """

        self._expires_in = expires_in

    @property
    def access_token(self) -> str:
        """Gets the access_token of this AuthResponse.

        Token de acceso JWT  # noqa: E501

        :return: The access_token of this AuthResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this AuthResponse.

        Token de acceso JWT  # noqa: E501

        :param access_token: The access_token of this AuthResponse.
        :type access_token: str
        """

        self._access_token = access_token
