# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorResponseError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, codigo: str=None, mensaje: str=None):  # noqa: E501
        """ErrorResponseError - a model defined in Swagger

        :param codigo: The codigo of this ErrorResponseError.  # noqa: E501
        :type codigo: str
        :param mensaje: The mensaje of this ErrorResponseError.  # noqa: E501
        :type mensaje: str
        """
        self.swagger_types = {
            'codigo': str,
            'mensaje': str
        }

        self.attribute_map = {
            'codigo': 'codigo',
            'mensaje': 'mensaje'
        }
        self._codigo = codigo
        self._mensaje = mensaje

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponseError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse_error of this ErrorResponseError.  # noqa: E501
        :rtype: ErrorResponseError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def codigo(self) -> str:
        """Gets the codigo of this ErrorResponseError.

        Código de error identificador  # noqa: E501

        :return: The codigo of this ErrorResponseError.
        :rtype: str
        """
        return self._codigo

    @codigo.setter
    def codigo(self, codigo: str):
        """Sets the codigo of this ErrorResponseError.

        Código de error identificador  # noqa: E501

        :param codigo: The codigo of this ErrorResponseError.
        :type codigo: str
        """

        self._codigo = codigo

    @property
    def mensaje(self) -> str:
        """Gets the mensaje of this ErrorResponseError.

        Mensaje descriptivo del error  # noqa: E501

        :return: The mensaje of this ErrorResponseError.
        :rtype: str
        """
        return self._mensaje

    @mensaje.setter
    def mensaje(self, mensaje: str):
        """Sets the mensaje of this ErrorResponseError.

        Mensaje descriptivo del error  # noqa: E501

        :param mensaje: The mensaje of this ErrorResponseError.
        :type mensaje: str
        """

        self._mensaje = mensaje
