# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.item_consulta import ItemConsulta  # noqa: F401,E501
from swagger_server.models.metadata import Metadata  # noqa: F401,E501
from swagger_server import util


class ExportResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: Metadata=None, salida_consulta: List[ItemConsulta]=None):  # noqa: E501
        """ExportResponse - a model defined in Swagger

        :param metadata: The metadata of this ExportResponse.  # noqa: E501
        :type metadata: Metadata
        :param salida_consulta: The salida_consulta of this ExportResponse.  # noqa: E501
        :type salida_consulta: List[ItemConsulta]
        """
        self.swagger_types = {
            'metadata': Metadata,
            'salida_consulta': List[ItemConsulta]
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'salida_consulta': 'salidaConsulta'
        }
        self._metadata = metadata
        self._salida_consulta = salida_consulta

    @classmethod
    def from_dict(cls, dikt) -> 'ExportResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExportResponse of this ExportResponse.  # noqa: E501
        :rtype: ExportResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this ExportResponse.


        :return: The metadata of this ExportResponse.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this ExportResponse.


        :param metadata: The metadata of this ExportResponse.
        :type metadata: Metadata
        """

        self._metadata = metadata

    @property
    def salida_consulta(self) -> List[ItemConsulta]:
        """Gets the salida_consulta of this ExportResponse.

        Resultados de la consulta  # noqa: E501

        :return: The salida_consulta of this ExportResponse.
        :rtype: List[ItemConsulta]
        """
        return self._salida_consulta

    @salida_consulta.setter
    def salida_consulta(self, salida_consulta: List[ItemConsulta]):
        """Sets the salida_consulta of this ExportResponse.

        Resultados de la consulta  # noqa: E501

        :param salida_consulta: The salida_consulta of this ExportResponse.
        :type salida_consulta: List[ItemConsulta]
        """

        self._salida_consulta = salida_consulta
