# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, juegos: List[str]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param juegos: The juegos of this InlineResponse2001.  # noqa: E501
        :type juegos: List[str]
        """
        self.swagger_types = {
            'juegos': List[str]
        }

        self.attribute_map = {
            'juegos': 'juegos'
        }
        self._juegos = juegos

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def juegos(self) -> List[str]:
        """Gets the juegos of this InlineResponse2001.


        :return: The juegos of this InlineResponse2001.
        :rtype: List[str]
        """
        return self._juegos

    @juegos.setter
    def juegos(self, juegos: List[str]):
        """Sets the juegos of this InlineResponse2001.


        :param juegos: The juegos of this InlineResponse2001.
        :type juegos: List[str]
        """

        self._juegos = juegos
