# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TiposLoteriaResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tipo_loteria: List[str]=None):  # noqa: E501
        """TiposLoteriaResponse - a model defined in Swagger

        :param tipo_loteria: The tipo_loteria of this TiposLoteriaResponse.  # noqa: E501
        :type tipo_loteria: List[str]
        """
        self.swagger_types = {
            'tipo_loteria': List[str]
        }

        self.attribute_map = {
            'tipo_loteria': 'tipoLoteria'
        }
        self._tipo_loteria = tipo_loteria

    @classmethod
    def from_dict(cls, dikt) -> 'TiposLoteriaResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TiposLoteriaResponse of this TiposLoteriaResponse.  # noqa: E501
        :rtype: TiposLoteriaResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tipo_loteria(self) -> List[str]:
        """Gets the tipo_loteria of this TiposLoteriaResponse.

        Lista de tipos de lotería disponibles  # noqa: E501

        :return: The tipo_loteria of this TiposLoteriaResponse.
        :rtype: List[str]
        """
        return self._tipo_loteria

    @tipo_loteria.setter
    def tipo_loteria(self, tipo_loteria: List[str]):
        """Sets the tipo_loteria of this TiposLoteriaResponse.

        Lista de tipos de lotería disponibles  # noqa: E501

        :param tipo_loteria: The tipo_loteria of this TiposLoteriaResponse.
        :type tipo_loteria: List[str]
        """
        allowed_values = ["triple", "terminal", "recargas", "multijuego", "juego-electronico", "animalito"]  # noqa: E501
        if not set(tipo_loteria).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `tipo_loteria` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(tipo_loteria) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._tipo_loteria = tipo_loteria
