# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TipoLoteriaJuegosResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tipo_loteria: str=None, juegos: List[str]=None):  # noqa: E501
        """TipoLoteriaJuegosResponse - a model defined in Swagger

        :param tipo_loteria: The tipo_loteria of this TipoLoteriaJuegosResponse.  # noqa: E501
        :type tipo_loteria: str
        :param juegos: The juegos of this TipoLoteriaJuegosResponse.  # noqa: E501
        :type juegos: List[str]
        """
        self.swagger_types = {
            'tipo_loteria': str,
            'juegos': List[str]
        }

        self.attribute_map = {
            'tipo_loteria': 'tipoLoteria',
            'juegos': 'juegos'
        }
        self._tipo_loteria = tipo_loteria
        self._juegos = juegos

    @classmethod
    def from_dict(cls, dikt) -> 'TipoLoteriaJuegosResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TipoLoteriaJuegosResponse of this TipoLoteriaJuegosResponse.  # noqa: E501
        :rtype: TipoLoteriaJuegosResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tipo_loteria(self) -> str:
        """Gets the tipo_loteria of this TipoLoteriaJuegosResponse.

        Tipo de lotería consultado  # noqa: E501

        :return: The tipo_loteria of this TipoLoteriaJuegosResponse.
        :rtype: str
        """
        return self._tipo_loteria

    @tipo_loteria.setter
    def tipo_loteria(self, tipo_loteria: str):
        """Sets the tipo_loteria of this TipoLoteriaJuegosResponse.

        Tipo de lotería consultado  # noqa: E501

        :param tipo_loteria: The tipo_loteria of this TipoLoteriaJuegosResponse.
        :type tipo_loteria: str
        """

        self._tipo_loteria = tipo_loteria

    @property
    def juegos(self) -> List[str]:
        """Gets the juegos of this TipoLoteriaJuegosResponse.

        Lista de juegos asociados al tipo de lotería  # noqa: E501

        :return: The juegos of this TipoLoteriaJuegosResponse.
        :rtype: List[str]
        """
        return self._juegos

    @juegos.setter
    def juegos(self, juegos: List[str]):
        """Sets the juegos of this TipoLoteriaJuegosResponse.

        Lista de juegos asociados al tipo de lotería  # noqa: E501

        :param juegos: The juegos of this TipoLoteriaJuegosResponse.
        :type juegos: List[str]
        """

        self._juegos = juegos
